spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:offline_billing_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:narenrajaa312}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 20000
      pool-name: OfflineBillingHikariPool

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 25
          order_inserts: true
          order_updates: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: '17'
    locations: classpath:db/migration

logging:
  level:
    root: INFO
    com.yourcompany.billing: DEBUG
    org.hibernate.SQL: INFO
