import { Category, CompanySetting, Customer, Invoice, Product, StockMovement, TaxRate, Unit } from './types';

export const initialCompanySettings: CompanySetting = {
  id: 1,
  companyName: 'Apex Retail & Wholesale',
  legalName: 'Apex Enterprise Pvt Ltd',
  addressLine1: '42 Commercial Boulevard, 1st Cross',
  city: 'Bengaluru',
  state: 'Karnataka',
  stateCode: '29',
  pincode: '560001',
  gstin: '29ABCDE1234F1Z5',
  phone: '+91 98765 43210',
  email: 'billing@apexretail.local',
  currencyCode: 'INR',
  invoicePrefix: 'INV',
};

export const initialUnits: Unit[] = [
  { id: 1, name: 'Piece', symbol: 'pcs' },
  { id: 2, name: 'Kilogram', symbol: 'kg' },
  { id: 3, name: 'Liter', symbol: 'L' },
  { id: 4, name: 'Box', symbol: 'box' },
  { id: 5, name: 'Pack', symbol: 'pack' },
];

export const initialCategories: Category[] = [
  { id: 1, name: 'Electronics & Audio', description: 'Gadgets, peripherals and audio equipment' },
  { id: 2, name: 'Groceries & Provisions', description: 'Daily staple foods and supplies' },
  { id: 3, name: 'Stationery & Office', description: 'Office paper, pens, and packing materials' },
  { id: 4, name: 'Hardware & Tools', description: 'Cables, fasteners, and maintenance tools' },
];

export const initialTaxRates: TaxRate[] = [
  { id: 1, name: 'Exempt (0%)', taxType: 'GST', cgstRate: 0, sgstRate: 0, igstRate: 0, cessRate: 0 },
  { id: 2, name: 'GST 5%', taxType: 'GST', cgstRate: 2.5, sgstRate: 2.5, igstRate: 5, cessRate: 0 },
  { id: 3, name: 'GST 12%', taxType: 'GST', cgstRate: 6, sgstRate: 6, igstRate: 12, cessRate: 0 },
  { id: 4, name: 'GST 18%', taxType: 'GST', cgstRate: 9, sgstRate: 9, igstRate: 18, cessRate: 0 },
  { id: 5, name: 'GST 28%', taxType: 'GST', cgstRate: 14, sgstRate: 14, igstRate: 28, cessRate: 0 },
];

export const initialProducts: Product[] = [
  {
    id: 1,
    sku: 'ELEC-LOGI-M220',
    barcode: '8901234567890',
    name: 'Logitech M220 Silent Wireless Mouse',
    description: 'Ultra-quiet 2.4GHz optical mouse with 18-month battery life',
    categoryId: 1,
    categoryName: 'Electronics & Audio',
    unitId: 1,
    unitSymbol: 'pcs',
    taxRateId: 4,
    taxRatePercent: 18,
    cgstRate: 9,
    sgstRate: 9,
    hsnCode: '84716060',
    costPrice: 550.0,
    sellingPrice: 799.0,
    trackStock: true,
    currentStock: 48,
    minimumStock: 10,
    reorderLevel: 15,
    targetStock: 60,
    isActive: true,
  },
  {
    id: 2,
    sku: 'ELEC-BOAT-141',
    barcode: '8909876543210',
    name: 'boAt Airdopes 141 ANC Earbuds',
    description: 'Active noise cancelling wireless bluetooth earphones 42H playtime',
    categoryId: 1,
    categoryName: 'Electronics & Audio',
    unitId: 1,
    unitSymbol: 'pcs',
    taxRateId: 4,
    taxRatePercent: 18,
    cgstRate: 9,
    sgstRate: 9,
    hsnCode: '85183000',
    costPrice: 900.0,
    sellingPrice: 1299.0,
    trackStock: true,
    currentStock: 25,
    minimumStock: 8,
    reorderLevel: 12,
    targetStock: 40,
    isActive: true,
  },
  {
    id: 3,
    sku: 'GROC-DAAWAT-BAS',
    barcode: '8901058852331',
    name: 'Daawat Rozana Super Basmati Rice 5kg',
    description: 'Long grain aromatic basmati rice for daily dining',
    categoryId: 2,
    categoryName: 'Groceries & Provisions',
    unitId: 4,
    unitSymbol: 'box',
    taxRateId: 2,
    taxRatePercent: 5,
    cgstRate: 2.5,
    sgstRate: 2.5,
    hsnCode: '10063020',
    costPrice: 380.0,
    sellingPrice: 475.0,
    trackStock: true,
    currentStock: 34,
    minimumStock: 10,
    reorderLevel: 15,
    targetStock: 50,
    isActive: true,
  },
  {
    id: 4,
    sku: 'STAT-JK-A4-75',
    barcode: '8902514001015',
    name: 'JK Copier A4 Paper Ream (500 Sheets, 75 GSM)',
    description: 'High brightness premium multipurpose photocopy & printer paper',
    categoryId: 3,
    categoryName: 'Stationery & Office',
    unitId: 5,
    unitSymbol: 'pack',
    taxRateId: 3,
    taxRatePercent: 12,
    cgstRate: 6,
    sgstRate: 6,
    hsnCode: '48025610',
    costPrice: 220.0,
    sellingPrice: 299.0,
    trackStock: true,
    currentStock: 92,
    minimumStock: 20,
    reorderLevel: 30,
    targetStock: 120,
    isActive: true,
  },
  {
    id: 5,
    sku: 'ELEC-SAND-64G',
    barcode: '8904123890123',
    name: 'SanDisk Ultra 64GB USB 3.0 Flash Drive',
    description: 'High-speed metal pen drive up to 130MB/s transfer speed',
    categoryId: 1,
    categoryName: 'Electronics & Audio',
    unitId: 1,
    unitSymbol: 'pcs',
    taxRateId: 4,
    taxRatePercent: 18,
    cgstRate: 9,
    sgstRate: 9,
    hsnCode: '85235100',
    costPrice: 380.0,
    sellingPrice: 549.0,
    trackStock: true,
    currentStock: 6, // Low stock demo!
    minimumStock: 10,
    reorderLevel: 15,
    targetStock: 50,
    isActive: true,
  },
];

export const initialCustomers: Customer[] = [
  {
    id: 1,
    customerCode: 'CUST-001',
    customerType: 'B2C',
    customerSegment: 'SMALL',
    name: 'Rahul Sharma',
    phone: '9845012345',
    email: 'rahul.s@outlook.com',
    city: 'Bengaluru',
    state: 'Karnataka',
    stateCode: '29',
    pincode: '560034',
    gstRegistered: false,
    defaultDiscountPercentage: 0,
    isActive: true,
  },
  {
    id: 2,
    customerCode: 'CUST-002',
    customerType: 'B2B',
    customerSegment: 'LARGE',
    name: 'GreenField Tech Solutions',
    companyName: 'GreenField Tech Solutions Pvt Ltd',
    contactPerson: 'Anand Verma',
    phone: '9880098800',
    email: 'accounts@greenfieldtech.in',
    addressLine1: 'Tower B, Tech Park, Outer Ring Road',
    city: 'Bengaluru',
    state: 'Karnataka',
    stateCode: '29',
    pincode: '560103',
    gstin: '29AAACG8976R1ZO',
    gstRegistered: true,
    defaultDiscountPercentage: 5,
    notes: 'Preferred corporate account - Net 15 commercial terms',
    isActive: true,
  },
  {
    id: 3,
    customerCode: 'CUST-003',
    customerType: 'B2B',
    customerSegment: 'LARGE',
    name: 'Apex Wholesale Traders',
    companyName: 'Apex Wholesale Traders LLP',
    contactPerson: 'Vikram Mehta',
    phone: '9876543211',
    email: 'purchases@apextraders.in',
    addressLine1: 'APMC Yard, Yeshwanthpur',
    city: 'Bengaluru',
    state: 'Karnataka',
    stateCode: '29',
    pincode: '560022',
    gstin: '29AABCA1234F1Z8',
    gstRegistered: true,
    defaultDiscountPercentage: 8,
    notes: 'Wholesale bulk buyer - 8% standard concession',
    isActive: true,
  },
  {
    id: 4,
    customerCode: 'CUST-004',
    customerType: 'B2C',
    customerSegment: 'SMALL',
    name: 'Sneha Patel',
    phone: '9811223344',
    email: 'sneha.patel@gmail.com',
    city: 'Bengaluru',
    state: 'Karnataka',
    stateCode: '29',
    pincode: '560001',
    gstRegistered: false,
    defaultDiscountPercentage: 0,
    isActive: true,
  },
  {
    id: 5,
    customerCode: 'CUST-005',
    customerType: 'B2B',
    customerSegment: 'LARGE',
    name: 'Prime Retail Corporation',
    companyName: 'Prime Retail Corp India Ltd',
    contactPerson: 'Rajesh Rao',
    phone: '9844001122',
    email: 'billing@primeretail.com',
    addressLine1: 'Commercial Complex, MG Road',
    city: 'Bengaluru',
    state: 'Karnataka',
    stateCode: '29',
    pincode: '560025',
    gstin: '29AAACR7145R1ZT',
    gstRegistered: true,
    defaultDiscountPercentage: 10,
    notes: 'Key regional enterprise buyer - 10% contract concession',
    isActive: true,
  },
];

export const initialInvoices: Invoice[] = [
  {
    id: 1,
    invoiceNumber: 'INV/2026-2027/00001',
    invoiceDate: new Date(Date.now() - 3600000 * 4).toISOString(),
    customerId: 1,
    customerName: 'Rahul Sharma',
    customerPhone: '9845012345',
    employeeId: 1,
    employeeName: 'Rajan (Cashier)',
    subtotal: 1348.0,
    discountTotal: 0.0,
    taxableAmount: 1142.37,
    cgstTotal: 102.81,
    sgstTotal: 102.81,
    igstTotal: 0.0,
    cessTotal: 0.0,
    roundOff: 0.01,
    grandTotal: 1348.0,
    paymentStatus: 'PAID',
    invoiceStatus: 'COMPLETED',
    items: [
      {
        id: 1,
        productId: 1,
        productName: 'Logitech M220 Silent Wireless Mouse',
        sku: 'ELEC-LOGI-M220',
        hsnCode: '84716060',
        quantity: 1,
        unitPrice: 799.0,
        discountPercentage: 0,
        discountAmount: 0,
        taxRate: 18,
        taxableAmount: 677.12,
        cgstAmount: 60.94,
        sgstAmount: 60.94,
        igstAmount: 0,
        cessAmount: 0,
        lineTotal: 799.0,
      },
      {
        id: 2,
        productId: 5,
        productName: 'SanDisk Ultra 64GB USB 3.0 Flash Drive',
        sku: 'ELEC-SAND-64G',
        hsnCode: '85235100',
        quantity: 1,
        unitPrice: 549.0,
        discountPercentage: 0,
        discountAmount: 0,
        taxRate: 18,
        taxableAmount: 465.25,
        cgstAmount: 41.87,
        sgstAmount: 41.87,
        igstAmount: 0,
        cessAmount: 0,
        lineTotal: 549.0,
      },
    ],
    payments: [
      {
        paymentMethod: 'UPI',
        amount: 1348.0,
        paymentReference: 'UPI-REF-992381283',
        paymentDate: new Date(Date.now() - 3600000 * 4).toISOString(),
      },
    ],
  },
];

export const initialStockMovements: StockMovement[] = [
  {
    id: 1,
    productId: 1,
    productName: 'Logitech M220 Silent Wireless Mouse',
    sku: 'ELEC-LOGI-M220',
    movementType: 'OPENING',
    quantity: 50,
    quantityBefore: 0,
    quantityAfter: 50,
    reason: 'Initial physical inventory audit count',
    createdBy: 'admin',
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: 2,
    productId: 1,
    productName: 'Logitech M220 Silent Wireless Mouse',
    sku: 'ELEC-LOGI-M220',
    movementType: 'SALE',
    quantity: 1,
    referenceType: 'INVOICE',
    referenceId: 1,
    quantityBefore: 50,
    quantityAfter: 49,
    reason: 'Invoice sale: INV/2026-2027/00001',
    createdBy: 'biller',
    createdAt: new Date(Date.now() - 3600000 * 4).toISOString(),
  },
];
